### PR TITLE
Fixed issue (#5) - Unnecessary use of Custom AppBar

### PR DESCRIPTION
**Pull request by rajitdeb**
Fixed issue (#5) - Unnecessary use of Custom AppBar. Also upgraded the dependencies to their compatible versions

### CODE REVIEW

**Comment by rajitdeb** [comment]
DO NOT MERGE THIS PR NOW. There are issues with this PR i am working on them will soon resolve them

**Comment by rajitdeb** [comment]
Now, you can merge the PR i have pushed a resolved commit @danascape

**Review by danascape — APPROVED** [review]

**Comment by danascape** [comment]
@rajitdeb you need to force push, it has conflicts

**Comment by danascape** [comment]
rebase the branch once

**Review by danascape — APPROVED** [review]

**Comment by rajitdeb** [comment]
Done resolving Conflicts. Please merge @danascape

**Review by danascape — APPROVED** [review]

**Pull request merged**
